services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
  App\:
    resource: '../src/{EventListener}'

  App\EventListener\UserListener:
    tags:
      - { name: doctrine.orm.entity_listener }

  App\EventListener\ApiListener:
    tags:
      - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 254 }
      - { name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority: -1 }

  App\EventListener\RedirectListener:
    tags:
      - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse, priority: 255}