app:
    resource: '../src/Controller/'
    type: annotation

api:
    resource: '../src/Controller/Api'
    type: annotation
    prefix: '/api/v1'

app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }
